-- 自动生成：python3 tests/prepare_ocean_ready_art.py；禁止手工编辑。
-- 只含图片规格，不含实体、玩法数值或更新逻辑。
return {
    barrel = {
        path = "image/OceanLoop/barrel.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 451, contentHeight = 451,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
        completeIsland = false,
    },
    boat = {
        path = "image/OceanWave2/boat.png",
        pixelWidth = 640, pixelHeight = 427,
        contentWidth = 563, contentHeight = 224,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
        completeIsland = false,
    },
    driftwood = {
        path = "image/OceanReady/driftwood.png",
        pixelWidth = 768, pixelHeight = 512,
        contentWidth = 676, contentHeight = 229,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
        completeIsland = false,
    },
    gull = {
        path = "image/OceanWave2/gull.png",
        pixelWidth = 384, pixelHeight = 384,
        contentWidth = 338, contentHeight = 205,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
        completeIsland = false,
    },
    gull_dive = {
        path = "image/OceanWave2/gull_dive.png",
        pixelWidth = 384, pixelHeight = 384,
        contentWidth = 338, contentHeight = 279,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
        completeIsland = false,
    },
    island = {
        path = "image/OceanWave2/island.png",
        pixelWidth = 768, pixelHeight = 768,
        contentWidth = 676, contentHeight = 622,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
        completeIsland = true,
    },
    reef = {
        path = "image/OceanReady/reef.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 451, contentHeight = 429,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
        completeIsland = false,
    },
    ripple = {
        path = "image/OceanWave2/ripple.png",
        pixelWidth = 256, pixelHeight = 256,
        contentWidth = 205, contentHeight = 143,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
        completeIsland = false,
    },
    sardine = {
        path = "image/OceanReady/sardine.png",
        pixelWidth = 768, pixelHeight = 512,
        contentWidth = 676, contentHeight = 182,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
        completeIsland = false,
    },
    shrub = {
        path = "image/OceanReady/shrub.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 419, contentHeight = 451,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
        completeIsland = false,
    },
    splash = {
        path = "image/OceanWave2/splash.png",
        pixelWidth = 256, pixelHeight = 256,
        contentWidth = 178, contentHeight = 97,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
        completeIsland = false,
    },
    waterpaper = {
        path = "image/OceanLoop/waterpaper.png",
        pixelWidth = 1024, pixelHeight = 1024,
        contentWidth = 1024, contentHeight = 1024,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = true,
        completeIsland = false,
    },
}
