-- 自动生成：python3 tests/prepare_ocean_ready_art.py；禁止手工编辑。
-- 只含图片规格，不含实体、玩法数值或更新逻辑。
return {
    barrel = {
        path = "image/OceanLoop/barrel.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 451, contentHeight = 451,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
    },
    boat = {
        path = "image/OceanLoop/boat.png",
        pixelWidth = 1024, pixelHeight = 512,
        contentWidth = 900, contentHeight = 451,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
    },
    gull = {
        path = "image/OceanLoop/gull.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 236, contentHeight = 451,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
    },
    island = {
        path = "image/OceanLoop/island.png",
        pixelWidth = 1024, pixelHeight = 1024,
        contentWidth = 900, contentHeight = 901,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
    },
    ripple = {
        path = "image/OceanLoop/ripple.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 444, contentHeight = 463,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
    },
    waterpaper = {
        path = "image/OceanLoop/waterpaper.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 512, contentHeight = 512,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = true,
    },
    driftwood = {
        path = "image/OceanReady/driftwood.png",
        pixelWidth = 768, pixelHeight = 512,
        contentWidth = 675, contentHeight = 228,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
    },
    reef = {
        path = "image/OceanReady/reef.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 451, contentHeight = 428,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
    },
    sardine = {
        path = "image/OceanReady/sardine.png",
        pixelWidth = 768, pixelHeight = 512,
        contentWidth = 675, contentHeight = 181,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
    },
    shrub = {
        path = "image/OceanReady/shrub.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 418, contentHeight = 450,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
    },
}
