-- 自动生成：python3 tests/prepare_ocean_ready_art.py；禁止手工编辑。
-- 只含图片规格，不含实体、玩法数值或更新逻辑。
return {
    barrel = {
        path = "image/OceanLoop/barrel.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 451, contentHeight = 451,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
    },
    boat = {
        path = "image/OceanLoop/boat.png",
        pixelWidth = 1024, pixelHeight = 512,
        contentWidth = 900, contentHeight = 451,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
    },
    gull = {
        path = "image/OceanLoop/gull.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 236, contentHeight = 451,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
    },
    island = {
        path = "image/OceanLoop/island.png",
        pixelWidth = 1024, pixelHeight = 1024,
        contentWidth = 900, contentHeight = 901,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
    },
    ripple = {
        path = "image/OceanLoop/ripple.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 444, contentHeight = 463,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = false,
    },
    waterpaper = {
        path = "image/OceanLoop/waterpaper.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 512, contentHeight = 512,
        anchorX = 0.5, anchorY = 0.5,
        preload = true,
        repeatTexture = true,
    },
    driftwood = {
        path = "image/OceanReady/driftwood.png",
        pixelWidth = 768, pixelHeight = 512,
        contentWidth = 675, contentHeight = 228,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
    },
    reef = {
        path = "image/OceanReady/reef.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 451, contentHeight = 428,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
    },
    sardine = {
        path = "image/OceanReady/sardine.png",
        pixelWidth = 768, pixelHeight = 512,
        contentWidth = 675, contentHeight = 181,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
    },
    shrub = {
        path = "image/OceanReady/shrub.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 418, contentHeight = 450,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
    },
    barrel_story = {
        path = "image/OceanStory_barrel_20261005115009.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 359, contentHeight = 378,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
    },
    boat_story = {
        path = "image/OceanStory_boat_20261005114947.png",
        pixelWidth = 768, pixelHeight = 1536,
        contentWidth = 459, contentHeight = 1355,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
    },
    gull_story = {
        path = "image/OceanStory_gull_20261005114946.png",
        pixelWidth = 512, pixelHeight = 512,
        contentWidth = 505, contentHeight = 263,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
    },
    island_story = {
        path = "image/OceanStory_island_20261005114948.png",
        pixelWidth = 1024, pixelHeight = 1024,
        contentWidth = 730, contentHeight = 739,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = false,
    },
    ocean_tile = {
        path = "image/reading_sea_watercolor_ocean_tile_20261005115327.png",
        pixelWidth = 1024, pixelHeight = 1024,
        contentWidth = 1024, contentHeight = 1024,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = true,
    },
    waterpaper_story = {
        path = "image/OceanStory_waterpaper_20261005114940.png",
        pixelWidth = 1024, pixelHeight = 1024,
        contentWidth = 1024, contentHeight = 1024,
        anchorX = 0.5, anchorY = 0.5,
        preload = false,
        repeatTexture = true,
    },
}
